#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements.txt
python3 -m pip install --requirement requirements_test.txt

hass --config "config" --script ensure_config

echo "Installing frontend dependencies…"
cd custom_components/loxone/frontend
npm install
echo "Building frontend panel…"
node build.mjs
